from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime
import requests
import pandas as pd

def trigger_fastapi_predictions():
    print("Loading preprocessed data...")
    # Load the data generated by DAG 1
    df = pd.read_csv("/opt/airflow/data/processed/final.csv")
    
    # 🚨 FIX: Force all missing values to 0 so JSON doesn't crash
    df = df.fillna(0)
    
    payload = df.to_dict(orient="records")
    
    print(f"Sending {len(payload)} records to FastAPI...")
    response = requests.post(
        "http://host.docker.internal:8000/predict_batch", 
        json=payload 
    )
    
    if response.status_code != 200:
        raise ValueError(f"API failed with status {response.status_code}: {response.text}")
    print("Batch predictions completed successfully!")

with DAG(
    '2_batch_inference',
    description='Triggers FastAPI for readmission predictions',
    schedule_interval=None,
    start_date=datetime(2026, 6, 20),
    catchup=False
) as dag:

    predict_task = PythonOperator(
        task_id='run_model_inference',
        python_callable=trigger_fastapi_predictions
    )   